server:
  port: 8090

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          microsoft:
#            client-id: ${AZURE_CLIENT_ID}
#            client-secret: ${AZURE_CLIENT_SECRET}
#            scope: openid, profile, email
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/microsoft"
#            client-name: Microsoft
#        provider:
#          microsoft:
#            authorization-uri: https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            jwk-set-uri: https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/discovery/v2.0/keys

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      connection-timeout: 3000

telegram:
  bot:
    username: ${BOT_USERNAME}
    token: ${BOT_TOKEN}
    admin-id: ${ADMIN_ID}  # Replace with your Telegram ID

application-config:
  admin-id: ${ADMIN_ID}
  maintenance-mode: 'OFF'
  maintenance-message: 'Sorry the service is under maintenance! Please try again later.'
  global-request-timeout-millisecond: 50000
  global-connect-timeout-millisecond: 10000
  microservices:
    ocs-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/services/surepay"
      request-timeout-millisecond: 4000
    sms-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/sms-transmit/v1/accounts/%s"
      request-timeout-millisecond: 4000
    billing-service:
      base-url: "https://prd-apiserver.camgsm.com.kh/services/proxyBilling"
      request-timeout-millisecond: 4000
    provisioning-service:
      request-timeout-millisecond: 15000
      base-url: "https://prd-apiserver.camgsm.com.kh/provisioning-gateway/v1"

logging:
  level:
    root: info